export const headerStyle: React.CSSProperties = {
    textAlign: 'center',
    padding: '0 12px',
    fontWeight: '600',
    fontSize: '16px',
    backgroundColor: 'var(--grey)',
    color: 'black',
    border: '1px solid var(--black)',
    position: 'sticky',
    top: '0px',
    zIndex: 1,
};
export const rowStyle: React.CSSProperties = {
    border: '1px solid var(--black)',
    background: 'var(--white)',
};
export const cellStyle: React.CSSProperties = {
    borderLeft: '1px solid var(--black)',
    padding: '1px',
    boxSizing: 'border-box',
};
export const cellSelection: React.CSSProperties = {
    borderLeft: '1px solid var(--black)',
    padding: '2px',
    textAlign: 'center',
    boxSizing: 'border-box',
};
export const options = {
    headerStyle,
    rowStyle,
    maxBodyHeight: '16.6rem',
    overflowY: 'visible',
    showEmptyDataSourceMessage: false,
    search: false,
    showTitle: false,
    paging: false,
    draggable: false,
    sorting: false,
};
export const initColumnsTable = () => [
    {
        title: 'C',
        field: 'selection',
        width: '40px',
        minWidth: 40,
        cellStyle: cellSelection,
        cellType: 'checkbox',
        sortAble: false,
    },
    {
        title: 'no',
        field: 'id',
        width: '1rem',
        minWidth: 40,
        cellStyle: cellStyle,
        sortAble: false,
    },
    {
        title: 'companyName',
        field: 'companyName',
        width: '5rem',
        minWidth: 40,
        cellStyle: cellStyle,
        sortAble: true,
    },
    {
        title: 'productCategory',
        field: 'productCategory',
        width: '7rem',
        minWidth: 40,
        cellStyle: cellStyle,
        sortAble: true,
    },
    {
        title: 'productHandled',
        field: 'productHandled',
        width: '10rem',
        minWidth: 40,
        cellStyle: cellStyle,
        sortAble: true,
    },
    {
        title: 'score',
        field: 'score',
        width: '25rem',
        cellStyle: cellStyle,
        minWidth: 40,
        cellType: 'Edit',
        sortAble: false,
        subTitle: [
            {
                title: 'Q',
                field: 'qualityScore',
                width: '1rem',
                minWidth: 40,
                cellStyle: cellStyle,
                sortAble: true,
            },
            {
                title: 'C',
                field: 'costScore',
                width: '1rem',
                minWidth: 40,
                cellStyle: cellStyle,
                sortAble: true,
            },
            {
                title: 'D',
                field: 'deliveryScore',
                width: '1rem',
                minWidth: 40,
                cellStyle: cellStyle,
                sortAble: true,
            },
            {
                title: 'F',
                field: 'financeScore',
                width: '1rem',
                minWidth: 40,
                cellStyle: cellStyle,
                sortAble: true,
            },
            {
                title: 'environmentScore',
                field: 'environmentScore',
                width: '2rem',
                minWidth: 40,
                cellStyle: cellStyle,
                sortAble: true,
            },
            {
                title: 'laborScore',
                field: 'laborScore',
                width: '2rem',
                minWidth: 40,
                cellStyle: cellStyle,
                sortAble: true,
            },
            {
                title: 'ethicsScore',
                field: 'ethicsScore',
                width: '2rem',
                minWidth: 40,
                cellStyle: cellStyle,
                sortAble: true,
            },
            {
                title: 'sustainableScore',
                field: 'sustainableScore',
                width: '2rem',
                minWidth: 40,
                cellStyle: cellStyle,
                sortAble: true,
            },
        ],
    },
    {
        title: 'searchForSupplier.totalMoney',
        field: 'totalMoney',
        width: '5rem',
        minWidth: 40,
        cellStyle: cellStyle,
        sortAble: true,
    },
    {
        title: 'searchForSupplier.totalDeliveries',
        field: 'totalDeliveries',
        width: '8rem',
        minWidth: 40,
        cellStyle: cellStyle,
        sortAble: true,
    },
    {
        title: 'xxx',
        field: 'xxx',
        width: '1rem',
        cellStyle: cellStyle,
    },
];
